// @ts-check
import { initSchema } from '@aws-amplify/datastore';
import { schema } from './schema';



const { CUSTOMER3RDPARTY, ACTIVITIESTP, ACTIVITIES360DSL, ACTIVITIES360DSLCUSTOMER360DSL, CUSTOMER360DSL, ACTIVITIESSTRAVA } = initSchema(schema);

export {
  CUSTOMER3RDPARTY,
  ACTIVITIESTP,
  ACTIVITIES360DSL,
  ACTIVITIES360DSLCUSTOMER360DSL,
  CUSTOMER360DSL,
  ACTIVITIESSTRAVA
};