/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_appsync_graphqlEndpoint": "https://yffoucqeyrd2fpmmd6nozkllmu.appsync-api.us-east-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-1",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-o2qsrbsqk5dq3nn7o2alonaryy",
    "aws_cloud_logic_custom": [
        {
            "name": "360dslWriteStravaNotification",
            "endpoint": "https://a6cragp76g.execute-api.us-east-1.amazonaws.com/staging",
            "region": "us-east-1"
        }
    ],
    "aws_cognito_identity_pool_id": "us-east-1:e664f9e5-c559-4591-b64e-411366ec0ae1",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_i7ZK2w9Iq",
    "aws_user_pools_web_client_id": "flt5r6jg1r0gl7q9dqcelpohg",
    "oauth": {}
};


export default awsmobile;
