/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_appsync_graphqlEndpoint": "https://yffoucqeyrd2fpmmd6nozkllmu.appsync-api.us-east-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-1",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-77xlche2zvanbka5sx6cphxiia",
    "aws_cloud_logic_custom": [
        {
            "name": "360dslWriteStravaNotification",
            "endpoint": "https://a6cragp76g.execute-api.us-east-1.amazonaws.com/staging",
            "region": "us-east-1"
        }
    ],
    "aws_cognito_identity_pool_id": "us-east-1:28fc1785-3de6-4076-8e4b-d5469fdf717d",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_WdskslhdA",
    "aws_user_pools_web_client_id": "6ulov1s12dvipdauhakdc4bkl",
    "oauth": {}
};


export default awsmobile;
